### ISSUE TITLE
Setup transifex

### ISSUE THREAD

**Issue by jaap3** [django-fiber/django-fiber#251]
The current transifex project for django-fiber (https://www.transifex.com/maz/django-fiber/) is not owned by anyone associated with this organisation. So we should look into setting up a django-fiber org on transifex as well. If at all possible it would be nice to transfer the current project to this new org.

Any volunteers that want to do this?

**Comment by richardbarran** [comment]
I'll do it.

**Comment by richardbarran** [comment]
I've set up [a new organisation](https://www.transifex.com/django-fiber/public/) on Transifex.

@jaap3 - can you initiate moving over the current Transifex project?

We need more admins for the Transifex organisation - at present I am the only member of 'django-fiber' on Transifex, so we have a bus factor of 1. That's not good.

I'd like more people to join as admins so that the project is safe for the future. @spookylukey @urban011 @jgentle I'm pinging you first as you're also been invited to django-fiber on Github. 

Other people who want to step forward as maintainers of the Transifex django-fiber project are of course welcome.

**Comment by spookylukey** [comment]
@richardbarran I'm happy to be a maintainer to increase the bus factor. I have no experience of actually using the platform.

**Comment by richardbarran** [comment]
@spookylukey no problems - I'm happy to maintain Transifex (there's not much to do) but it's better to have a few more people who can administer the account. Can you create an account on Transifex and post your username here please?

**Comment by spookylukey** [comment]
@richardbarran done, I'm `spookylukey` there too.

**Comment by jaap3** [comment]
@richardbarran I'm not part of the "old" transifex project (https://www.transifex.com/maz/django-fiber/), @dbunskoek is but I believe he doesn't have sufficient rights. It's probably best to contact the owner through transifex (https://www.transifex.com/user/profile/maz/) and see if he's able to transfer things.

**Comment by luzfcb** [comment]
Hello, I'm `maz` on transifex. Sorry for the very long delay, gmail was marking as spam the transifex messages.

@dbunskoek @jaap3 @richardbarran I can transfer ownership. Can you tell me which user / organization should receive it?

**Comment by luzfcb** [comment]
@dbunskoek @jaap3 @richardbarran I made the transfer to https://www.transifex.com/django-fiber/ . Now, an administrator of that organization must accept the ownership transfer

**Comment by richardbarran** [comment]
@luzfcb Ownership transferred! I will test synching the current project text strings with Transifex at the weekend.

**Comment by richardbarran** [comment]
The django-fiber project syncs correctly with the Transifex page. I have added a page in the wiki [as a crib-sheet for doing this in future](https://github.com/django-fiber/django-fiber/wiki/Project-maintainers'-guide).
Thanks @luzfcb for your help!

**Comment by jaap3** [comment]
Thanks @luzfcb and @richardbarran
